-- ============================================================================
-- One-off in-app announcement for the 2026-06-30 update.
-- Run ONCE against the production database after deploying the new code.
--
--   docker compose exec -T db mysql -uroot -p"$DB_PASS" "$DB_NAME" < deploy/2026-06-30_update_notice.sql
--   (or paste into phpMyAdmin > SQL)
--
-- Idempotent: re-running it will NOT create duplicate notifications.
-- Targets every non-supplier user (suppliers have their own portal).
-- ============================================================================

INSERT INTO notifications (user_id, type, title, body, link)
SELECT u.id,
       'software',
       'Software update v1.2',
       'Trip History now lets you view item details and edit or delete a trip (stock is auto-corrected). Every PDF report is now signed "Generated by GrowGig Inventory System (GIS)", and the Sales Report error has been fixed.',
       'mobile.php'
FROM users u
WHERE u.role <> 'supplier'
  AND NOT EXISTS (
      SELECT 1 FROM notifications n
      WHERE n.user_id = u.id
        AND n.title   = 'Software update v1.2'
  );
